### ISSUE TITLE
Issues with data set acquisition 

### ISSUE THREAD

**Issue by ishaanpbs** [statOmics/stageR#2]
The dataset mentioned is not available could you please make it available here.

kallisto data: RNA-seq analysis of prostate cancer in the Chinese population identifies recurrent gene fusions, cancer-associated long noncoding RNAs and aberrant alternative splicings. Downloaded from http://lair.berkeley.edu/eswaran12/?

Thanks

**Comment by koenvandenberge** [comment]
Thanks for noticing @ishaanpbs , it indeed seems like the 'The Lair' website is down.
If only interested in going through the vignette, you can get a subset of the data through

```
library(stageR)
data("esetProstate")
```

If you are interested in the full dataset, I have temporarily uploaded it on Dropbox and it is available through [this link](https://www.dropbox.com/s/r46yni5y8qhkse4/kallisto_table_unnormalized_unfiltered.csv?dl=0)

**Comment by ishaanpbs** [comment]
Thanks  !!
