### ISSUE TITLE
I think the use of "." to join gene and transcript is causing problems with Ensembl versions

### ISSUE THREAD

**Issue by mikelove** [statOmics/stageR#4]
hi Koen,

Here you `paste0` gene and transcript IDs with a "." and later use `strsplit`.

I found that this gave an error from `getAdjustedPValues` with Ensembl transcripts and genes that have version numbers. Splitting the IDs upstream solved the problem, but adds to the code required to run stageR

https://github.com/statOmics/stageR/blob/691ab97caaf111ab48948a9d8239f842b54ad5f7/R/accessors.R#L165-L166

**Comment by statOmics** [comment]
Hi Mike,

Thank you for reporting. I did not consider that this could occur.
Replacing the "." with "_" will also cause problems with e.g. RefSeq annotation.
Would it suit your case if I replace the "." with ":" for now?

I am thinking of switching to tidyverse nested data frames where every row is gene-level information and nested columns contain transcript-level information, but this will take some more time.

Koen

**Comment by mikelove** [comment]
DEXSeq uses ":" and SUPPA uses ";". I think both seem safe.

I'd have to think about the tidyverse approach and whether that'd make it easier or harder to work with stageR output :)

**Comment by statOmics** [comment]
Ok, good. The "." has now been replaced with ":" in commit 7027b18ffda95bf13b00c585c79d1c5c6bbec778
