### ISSUE TITLE
Error with getAdjustedPValues

### ISSUE THREAD

**Issue by sdwien** [statOmics/stageR#9]
Related to issue #8 , after successfully running `stageWiseAdjustment` , `getSignificantGenes` and `getSignificantTx` , I am getting an error with 
`getAdjustedPValues(stageRObj, order = TRUE, onlySignificantGenes = FALSE)`
saying:
```
The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run. 

Error in object@adjustedP[unlist(idListOrdTx), ] : 
  subscript out of bounds
```
I am using stageR_1.7.0 (with your recent changes fixing the problems in the previous steps) and the same data set I shared with you before.
Do you have any idea what could be causing that?
Many thanks,
best,
Sophia
Best

**Comment by koenvandenberge** [comment]
Hi,

My apologies for my late reply and encountering these issues.
This was related to the NA p-values in the DRIMSeq results, as before, and should be fixed with the newest commit.

Thank you again for letting me know about this.
Best,
Koen

**Comment by sdwien** [comment]
Works neatly now, many thanks again for fixing this! 
Best, Sophia
